version: '3'
services:
  web:
    build: .
    command: /bin/sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py createcachetable && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
